### PR TITLE
Use another package cron-expression

### LINKED ISSUE #52: Use another package cron-expression
According to the [answer on my issue](https://github.com/mtdowling/cron-expression/issues/173), I would like yii2-scheduling switched to a new package of cron-expression - [dragonmantank/cron-expression](https://github.com/dragonmantank/cron-expression).

### PR DESCRIPTION
**Pull request by hirenbhut93**
Resolved #52

### CODE REVIEW

**Comment by gietos** [comment]
dragonmantank/cron-expression v2.0 will require php v7. We should use older version, latest supporting php 5 I can see is v1.2.1

**Comment by JimChenWYU** [comment]
Or we should also release 2.0 for dragonmantank/cron-expression v2 ?

**Comment by gietos** [comment]
That is a great idea @JimChenWYU and of course we should do that, but in separate issue since there's stuff to do: to check other packages dependencies and to check code compatibility

**Comment by JimChenWYU** [comment]
@gietos I suggest to use this tools to check our code when upgrade from php5 to php7, it'is too convenient.   : )
1. https://github.com/sstalle/php7cc
2. https://github.com/phan/phan
3. https://github.com/phpstan/phpstan

**Comment by gietos** [comment]
Thanks for your suggestions @JimChenWYU, yet I'd move this conversation into a separate issue and keep this thread for pull request discussion

**Comment by theonedemon** [comment]
up?

**Comment by kstkn** [comment]
Closing this for now. Will create separate PR to switch to the version of the library that supports php v5.*

**Comment by kstkn** [comment]
https://github.com/omnilight/yii2-scheduling/pull/56

**Pull request closed without merging**
